### ISSUE TITLE
No longer seems to work

### ISSUE THREAD

**Issue by Kommynct** [DavidDeprost/mpv-autosub#45]
```
[autosub] No English subtitles were detected
[autosub] => Proceeding to download:
[autosub] Searching English subtitles ...
[autosub] Traceback (most recent call last):
[autosub]   File "/usr/bin/subliminal", line 33, in <module>
[autosub]     sys.exit(load_entry_point('subliminal==2.1.0', 'console_scripts', 'subliminal')())
[autosub]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[autosub]   File "/usr/bin/subliminal", line 25, in importlib_load_entry_point
[autosub]     return next(matches).load()
[autosub]            ^^^^^^^^^^^^^^^^^^^^
[autosub]   File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
[autosub]     module = import_module(match.group('module'))
[autosub]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[autosub]   File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
[autosub]     return _bootstrap._gcd_import(name[level:], package, level)
[autosub]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[autosub]   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
[autosub]   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
[autosub]   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
[autosub]   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
[autosub]   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
[autosub]   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
[autosub]   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
[autosub]   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
[autosub]   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
[autosub]   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
[autosub]   File "/usr/lib/python3.12/site-packages/subliminal/__init__.py", line 11, in <module>
[autosub]     from .core import (AsyncProviderPool, ProviderPool, check_video, download_best_subtitles, download_subtitles,
[autosub]   File "/usr/lib/python3.12/site-packages/subliminal/core.py", line 11, in <module>
[autosub]     from babelfish import Language, LanguageReverseError
[autosub]   File "/usr/lib/python3.12/site-packages/babelfish/__init__.py", line 14, in <module>
[autosub]     from .converters import (LanguageConverter, LanguageReverseConverter, LanguageEquivalenceConverter, CountryConverter,
[autosub]   File "/usr/lib/python3.12/site-packages/babelfish/converters/__init__.py", line 5, in <module>
[autosub]     from pkg_resources import iter_entry_points, EntryPoint
[autosub]   File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3324, in <module>
[autosub]     @_call_aside
[autosub]      ^^^^^^^^^^^
[autosub]   File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3299, in _call_aside
[autosub]     f(*args, **kwargs)
[autosub]   File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 3337, in _initialize_master_working_set
[autosub]     working_set = WorkingSet._build_master()
[autosub]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
[autosub]   File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 631, in _build_master
[autosub]     ws.require(__requires__)
[autosub]   File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 968, in require
[autosub]     needed = self.resolve(parse_requirements(requirements))
[autosub]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[autosub]   File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 829, in resolve
[autosub]     dist = self._resolve_dist(
[autosub]            ^^^^^^^^^^^^^^^^^^^
[autosub]   File "/usr/lib/python3.12/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
[autosub]     raise DistributionNotFound(req, requirers)
[autosub] pkg_resources.DistributionNotFound: The 'rarfile>=2.7' distribution was not found and is required by subliminal
[autosub] No English subtitles found
[autosub]
[autosub] No subtitles were found
```

**Comment by Kommynct** [comment]
Nevermind, I didn't uninstall either of these things and it was working previously, but for some reason I needed to install python-rarfile and python-enzyme, no clue, closing.
